name = "Panzerbrigade 21 Framework v0.0.0";
picture = "logo_pb21f_ca.paa";
actionName = "Website";
action = "https://github.com/vpzbrig21/pb21_framework";
description = "Bugtracker: https://github.com/vpzbrig21/pb21_framework/issues<br />Documentation: https://github.com/vpzbrig21/pb21_framework/docs/files/overview-txt.html";
logo = "logo_pb21f_ca.paa";
logoOver = "logo_pb21f_ca.paa";
tooltip = "Panzerbrigade 21 Framework";
tooltipOwned = "Panzerbrigade 21 Framework Owned";
overview = "Panzerbrigade 21 Framework";
author = "PzBrig21 S4";
overviewPicture = "logo_pb21f_ca.paa";
overviewText = "Panzerbrigade 21 Framework overviewText";
overviewFootnote = "<br /><br /><t color='#999999'>This content is under GPLv3 License.<br />Press <t /><t color='#19d3ff'>Left Shift + P<t /><t color='#999999'> to open the store page for more information.<t />";