name = "Panzerbrigade 21 Framework"
prefix = "pb21f"
author = "PzBrig21 S4"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_pb21f_ca.paa",
    "meta.cpp",
]

[version]
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
]