class CfgUniformDetails
{
	class gm_fc_ge {
		class serviceBranches {
			none[] = {"None","",""};
			ge_artillery[] = {"Artillery","#(argb,8,8,3)color(0.627,0.153,0.145,1,CO)",""};
			ge_nbc[] = {"NBC","#(argb,8,8,3)color(0.412,0.098,0.231,1,CO)",""};
			ge_antiair[] = {"Anti Air","#(argb,8,8,3)color(0.65098,0,0,1.0,CO)",""};
			ge_antitank[] = {"Anti Armor","#(argb,8,8,3)color(0.996078,0.588235,0.8,1.0,CO)",""};
			ge_armor[] = {"Armored","#(argb,8,8,3)color(0.827,0.329,0.373,1,CO)",""};
			ge_armorrecon[] = {"Armored Reconnaissance","#(argb,8,8,3)color(0.870588,0.478431,0.121569,1.0,CO)",""};
			ge_militarypolice[] = {"Military Police","#(argb,8,8,3)color(0.91,0.329,0.051,1,CO)",""};
			ge_signals[] = {"Signal Corps","#(argb,8,8,3)color(0.992,0.855,0.22,1,CO)",""};
			ge_infantry[] = {"Infantry","#(argb,8,8,3)color(0,0.435,0.263,1,CO)",""};
			ge_paratrooper[] = {"Paratroopers","#(argb,8,8,3)color(0.0941176,0.470588,0.192157,1.0,CO)",""};
			ge_mechinf[] = {"Mechanized Infantry","#(argb,8,8,3)color(0.0941176,0.470588,0.192157,1.0,CO)",""};
			ge_mntninf[] = {"Mountain Infantry","#(argb,8,8,3)color(0.0941176,0.470588,0.192157,1.0,CO)",""};
			ge_supply[] = {"Supply Corps","#(argb,8,8,3)color(0.00392157,0.25098,0.819608,1.0,CO)",""};
			ge_medical[] = {"Medical Corps","#(argb,8,8,3)color(0,0.129412,0.27451,1.0,CO)",""};
			ge_armyaviation[] = {"Army Aviation","#(argb,8,8,3)color(0.619608,0.619608,0.619608,1.0,CO)",""};
			ge_maintenance[] = {"Maintenance","#(argb,8,8,3)color(0.00392157,0.25098,0.819608,1.0,CO)",""};
			ge_engineer[] = {"Engineering","#(argb,8,8,3)color(0.156863,0.156863,0.156863,1.0,CO)",""};
			ge_music[] = {"Musical Detail","#(argb,8,8,3)color(1,1,1,1.0,CO)",""};
			ge_airforce[] = {"Airforce","",""};
			ge_generals[] = {"Generals","#(argb,8,8,3)color(0.65098,0,0,1.0,CO)",""};
			ge_aides[] = {"Aides","#(argb,8,8,3)color(0.827451,0.0705882,0.486275,1.0,CO)",""};
			ge_navy[] = {"Federal Navy","#(argb,8,8,3)color(0,0,0,0,CO)",""};
		};
		class rankInsignias	{
			class army_blk {
				displayName = "Army (Black)";
				gm_ge_or1_s[] = {"Schütze","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or1_s_blk"};
				gm_ge_or2_g[] = {"Gefreiter","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or2_g_blk","PRIVATE"};
				gm_ge_or3_og[] = {"Obergefreiter","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or3_og_blk"};
				gm_ge_or4_hg[] = {"Hauptgefreiter","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or3_hg_blk","CORPORAL"};
				gm_ge_or4_sg[] = {"Stabsgefreiter","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or4_sg_blk"};
				gm_ge_or4_osg[] = {"Oberstabsgefreiter","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or4_osg_blk"};
				gm_ge_or5_u[] = {"Unteroffizier","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or5_u_blk"};
				gm_ge_or5_su[] = {"Stabsunteroffizier","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or5_su_blk"};
				gm_ge_or6_f[] = {"Feldwebel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or6_f_blk","SERGEANT"};
				gm_ge_or6_of[] = {"Oberfeldwebel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or6_of_blk"};
				gm_ge_or7_hf[] = {"Hauptfeldwebel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or7_hf_blk"};
				gm_ge_or8_sf[] = {"Stabsfeldwebel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or8_sf_blk"};
				gm_ge_or9_osf[] = {"Oberstabsfeldwebel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_or9_osf_blk"};
				gm_ge_of1_l[] = {"Leutnant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_of1_l_blk","LIEUTENANT"};
				gm_ge_of1_ol[] = {"Oberleutnant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_of1_ol_blk"};
				gm_ge_of2_h[] = {"Hauptmann","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_of2_h_blk","CAPTAIN"};
				gm_ge_of2_sh[] = {"Stabshauptmann","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_of2_sh_blk"};
				gm_ge_of3_m[] = {"Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_of3_m_blk","MAJOR"};
				gm_ge_of4_otl[] = {"Oberstleutnant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_of4_otl_blk"};
				gm_ge_of5_o[] = {"Oberst","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_blk\gm_ge_of5_o_blk","COLONEL"};
				gm_ge_of6_bg[] = {"Brigadegeneral","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_gld\gm_ge_of6_bg_gld"};
				gm_ge_of7_gm[] = {"Generalmajor","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_gld\gm_ge_of7_gm_gld"};
				gm_ge_of8_gl[] = {"General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_gld\gm_ge_of8_gl_gld"};
			};
			class army_wht {
				displayName = "Army (Silver)";
				gm_ge_or1_s[] = {"Soldier","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or1_s_wht"};
				gm_ge_or2_g[] = {"Private","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or2_g_wht","PRIVATE"};
				gm_ge_or3_og[] = {"Private 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or3_og_wht"};
				gm_ge_or4_hg[] = {"Private 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or3_hg_wht","CORPORAL"};
				gm_ge_or4_sg[] = {"Private 3rd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or4_sg_wht"};
				gm_ge_or4_osg[] = {"Private 4th Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or4_osg_wht"};
				gm_ge_or5_u[] = {"Lance Corporal","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or5_u_wht"};
				gm_ge_or5_su[] = {"Corporal","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or5_su_wht"};
				gm_ge_or6_f[] = {"Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or6_f_wht","SERGEANT"};
				gm_ge_or6_of[] = {"Staff Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or6_of_wht"};
				gm_ge_or7_hf[] = {"Chief Petty Officer, 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or7_hf_wht"};
				gm_ge_or8_sf[] = {"Corp Sergeant Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or8_sf_wht"};
				gm_ge_or9_osf[] = {"Field Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_or9_osf_wht"};
				gm_ge_of1_l[] = {"Lieutenant 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_of1_l_wht","LIEUTENANT"};
				gm_ge_of1_ol[] = {"Lieutenant 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_of1_ol_wht"};
				gm_ge_of2_h[] = {"Captain","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_of2_h_wht","CAPTAIN"};
				gm_ge_of2_sh[] = {"Staff Captain","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_of2_sh_wht"};
				gm_ge_of3_m[] = {"Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_of3_m_wht","MAJOR"};
				gm_ge_of4_otl[] = {"Lieutenant Colonel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_of4_otl_wht"};
				gm_ge_of5_o[] = {"Colonel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_wht\gm_ge_of5_o_wht","COLONEL"};
				gm_ge_of6_bg[] = {"Brigadier General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_gld\gm_ge_of6_bg_gld"};
				gm_ge_of7_gm[] = {"Major General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_gld\gm_ge_of7_gm_gld"};
				gm_ge_of8_gl[] = {"Lieutenant General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\army_gld\gm_ge_of8_gl_gld"};
			};
			class airforce_wht	{
				displayName = "Airforce (Silver)";
				gm_ge_or1_s[] = {"Soldier","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or1_s_wht"};
				gm_ge_or2_g[] = {"Private","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or2_g_wht","PRIVATE"};
				gm_ge_or3_og[] = {"Private 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or3_og_wht"};
				gm_ge_or4_hg[] = {"Private 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or3_hg_wht","CORPORAL"};
				gm_ge_or4_sg[] = {"Private 3rd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or4_sg_wht"};
				gm_ge_or4_osg[] = {"Private 4th Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or4_osg_wht"};
				gm_ge_or5_u[] = {"Lance Corporal","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or5_u_wht"};
				gm_ge_or5_su[] = {"Corporal","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or5_su_wht"};
				gm_ge_or6_f[] = {"Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or6_f_wht","SERGEANT"};
				gm_ge_or6_of[] = {"Staff Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or6_of_wht"};
				gm_ge_or7_hf[] = {"Chief Petty Officer, 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or7_hf_wht"};
				gm_ge_or8_sf[] = {"Corp Sergeant Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or8_sf_wht"};
				gm_ge_or9_osf[] = {"Field Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_or9_osf_wht"};
				gm_ge_of1_l[] = {"Lieutenant 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_of1_l_wht","LIEUTENANT"};
				gm_ge_of1_ol[] = {"Lieutenant 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_of1_ol_wht"};
				gm_ge_of2_h[] = {"Captain","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_of2_h_wht","CAPTAIN"};
				gm_ge_of2_sh[] = {"Staff Captain","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_of2_sh_wht"};
				gm_ge_of3_m[] = {"Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_of3_m_wht","MAJOR"};
				gm_ge_of4_otl[] = {"Lieutenant Colonel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_of4_otl_wht"};
				gm_ge_of5_o[] = {"Colonel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_wht\gm_ge_of5_o_wht","COLONEL"};
				gm_ge_of6_bg[] = {"Brigadier General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_gld\gm_ge_of6_bg_gld"};
				gm_ge_of7_gm[] = {"Major General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_gld\gm_ge_of7_gm_gld"};
				gm_ge_of8_gl[] = {"Lieutenant General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_gld\gm_ge_of8_gl_gld"};
			};
			class airforce_blk	{
				displayName = "Airforce (Black)";
				gm_ge_or1_s[] = {"Soldier","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or1_s_blk"};
				gm_ge_or2_g[] = {"Private","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or2_g_blk","PRIVATE"};
				gm_ge_or3_og[] = {"Private 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or3_og_blk"};
				gm_ge_or4_hg[] = {"Private 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or3_hg_blk","CORPORAL"};
				gm_ge_or4_sg[] = {"Private 3rd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or4_sg_blk"};
				gm_ge_or4_osg[] = {"Private 4th Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or4_osg_blk"};
				gm_ge_or5_u[] = {"Lance Corporal","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or5_u_blk"};
				gm_ge_or5_su[] = {"Corporal","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or5_su_blk"};
				gm_ge_or6_f[] = {"Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or6_f_blk","SERGEANT"};
				gm_ge_or6_of[] = {"Staff Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or6_of_blk"};
				gm_ge_or7_hf[] = {"Chief Petty Officer, 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or7_hf_blk"};
				gm_ge_or8_sf[] = {"Corp Sergeant Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or8_sf_blk"};
				gm_ge_or9_osf[] = {"Field Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_or9_osf_blk"};
				gm_ge_of1_l[] = {"Lieutenant 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_of1_l_blk","LIEUTENANT"};
				gm_ge_of1_ol[] = {"Lieutenant 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_of1_ol_blk"};
				gm_ge_of2_h[] = {"Captain","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_of2_h_blk","CAPTAIN"};
				gm_ge_of2_sh[] = {"Staff Captain","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_of2_sh_blk"};
				gm_ge_of3_m[] = {"Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_of3_m_blk","MAJOR"};
				gm_ge_of4_otl[] = {"Lieutenant Colonel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_of4_otl_blk"};
				gm_ge_of5_o[] = {"Colonel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_blk\gm_ge_of5_o_blk","COLONEL"};
				gm_ge_of6_bg[] = {"Brigadier General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_gld\gm_ge_of6_bg_gld"};
				gm_ge_of7_gm[] = {"Major General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_gld\gm_ge_of7_gm_gld"};
				gm_ge_of8_gl[] = {"Lieutenant General","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\airforce_gld\gm_ge_of8_gl_gld"};
			};
			class navy {
				displayName = "Navy";
				gm_ge_or1_s[] = {"Sailor","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or1_s_navy"};
				gm_ge_or2_g[] = {"Private","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or2_g_navy","PRIVATE"};
				gm_ge_or3_og[] = {"Private 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or3_og_navy"};
				gm_ge_or4_hg[] = {"Private 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or3_hg_navy","CORPORAL"};
				gm_ge_or4_sg[] = {"Private 3rd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or4_sg_navy"};
				gm_ge_or4_osg[] = {"Private 4th Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or4_osg_navy"};
				gm_ge_or5_u[] = {"Petty Officer","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or5_u_navy"};
				gm_ge_or5_su[] = {"Petty Officer, 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or5_su_navy"};
				gm_ge_or6_f[] = {"Petty Offiecer, 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or6_f_navy","SERGEANT"};
				gm_ge_or6_of[] = {"Chief Petty Officer, 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or6_of_navy"};
				gm_ge_or7_hf[] = {"Sergeant Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or7_hf_navy"};
				gm_ge_or8_sf[] = {"Master Sergeant","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or8_sf_navy"};
				gm_ge_or9_osf[] = {"Sergeant Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_or9_osf_navy"};
				gm_ge_of1_l[] = {"Lieutenant 2nd Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_of1_l_navy","LIEUTENANT"};
				gm_ge_of1_ol[] = {"Lieutenant 1st Class","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_of1_ol_navy"};
				gm_ge_of2_h[] = {"Captain","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_of2_h_navy","CAPTAIN"};
				gm_ge_of2_sh[] = {"Staff Captain","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_of2_sh_navy"};
				gm_ge_of3_m[] = {"Major","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_of3_m_navy","MAJOR"};
				gm_ge_of4_otl[] = {"Lieutenant Colonel","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_of4_otl_navy"};
				gm_ge_of5_o[] = {"","\gm\gm_characters\gm_ge_characters\data\uniform\ranks\navy\gm_ge_of5_o_navy","COLONEL"};
			};
		};
		class armbands {
			gm_ge_armband_none[] = {"None","",""};
			gm_ge_armband_ao[] = {"AO","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_ao.rvmat"};
			gm_ge_armband_bvw[] = {"BvW","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_bvw.rvmat"};
			gm_ge_armband_fvw[] = {"FvW","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_fvw.rvmat"};
			gm_ge_armband_green[] = {"Green","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_green.rvmat"};
			gm_ge_armband_gvd[] = {"GvD","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_gvd.rvmat"};
			gm_ge_armband_ld[] = {"LD","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_ld.rvmat"};
			gm_ge_armband_leitender[] = {"Commanding","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_leitender.rvmat"};
			gm_ge_armband_mp[] = {"MP","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_mp.rvmat"};
			gm_ge_armband_mpdienst[] = {"MP Detail","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_mpdienst.rvmat"};
			gm_ge_armband_mvd[] = {"MvD","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_mvd.rvmat"};
			gm_ge_armband_nato_mp[] = {"MP (NATO)","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_nato_mp.rvmat"};
			gm_ge_armband_red[] = {"Red","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_red.rvmat"};
			gm_ge_armband_san[] = {"Medic","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_san.rvmat"};
			gm_ge_armband_sanhelfer[] = {"Medical detail","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_sanhelfer.rvmat"};
			gm_ge_armband_streife[] = {"Patrol","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_streife.rvmat"};
			gm_ge_armband_transport[] = {"Transport","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_transport.rvmat"};
			gm_ge_armband_uu[] = {"Accident Investigation","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_uu.rvmat"};
			gm_ge_armband_uvd[] = {"UvD","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_uvd.rvmat"};
			gm_ge_armband_wache[] = {"Guard","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_wache.rvmat"};
			gm_ge_armband_white[] = {"White","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_co.paa","\gm\gm_characters\gm_ge_characters\data\uniform\armband\gm_ge_armband_white.rvmat"};
		};
	};
};
